build:
	clear && g++ \
	main.cpp \
	gui/GUI.cpp \
	gui/subwins/ASubwin.cpp \
	-std=c++2a -Igui -Icommon \
	-lsfml-graphics -lsfml-window -lsfml-system

debug:
	clear && g++ \
	main.cpp \
	gui/GUI.cpp \
	gui/utils/ASubwin.cpp \
	-g3 -std=c++2a -Igui -Icommon \
	-lsfml-graphics -lsfml-window -lsfml-system
